### PR TITLE
Add loop control to simplify yaml templates

### LINKED ISSUE #47: Apply loop controls to yaml templates
Apply jinja looping controls to the `parm/templates` to reduce the size/complexity of the templates.

Figure out a way to iterate over the construct of PDATE, PDATEm6, PDATEm12, etc.

### PR DESCRIPTION
**Pull request by EdwardSafford-NOAA**
This is the first cut at simplifying yaml templates with loop controls.  I've condensed the 'PDATEm*' values into a list and then iterate over it to generate the necessary file names.  

I had hopes of generating the PDATEm* list dynamically, but after bashing my head against it (and ChatGPT's hallucinations) for the past 3 days I'm not convinced that is possible.  The next step to pursue a solution like that, I think, is to create a clean jinja2 environment apart from wxflow's extension and see if developing such a solution is possible.  Within the wxflow's additions I can't generate any useful debug information -- the debug attempts result in parsing exceptions and no useful output.

So this draft is mostly a status check.  If the changes to the one file here is an acceptable solution I can change the other yaml template plot files accordingly.   If I should continue pursuing dynamic generation of the list, then I will do that.

Closes #47 (some day).

### CODE REVIEW

**Review by CoryMartin-NOAA — COMMENTED** [review]
Is this helpful:
```
{% set offset_td = "-6H" | to_timedelta %}
{% set PDATEnew = PDATE | add_to_datetime(offset_td) %}
```
this, assuming that PDATE is a python datetime object

**Comment by EdwardSafford-NOAA** [comment]
Maybe.  What you suggest does work for the 2nd cycle (PDATE -6).  What I need to do is iterate that solution over 121 cycles.  I've tried this for the first 2 cycles but it's not working.  I have no output at all from this, so I'm guessing the conversion of ii to string isn't working, even though the `~` is supposed to accomplish that.

```   
      {% for i in range(6, 2, 6) %}
      {% set offset_td = "-" ~ ii ~ "H" | to_timedelta %}
      {% set PDATEnew = PDATE | add_to_datetime(offset_td) %}
      - {{ DATA }}/time.{{ SENSOR }}_{{ SAT }}.{{ PDATEnew | to_YMDH }}.ieee_d
      {% endfor %}```

**Comment by CoryMartin-NOAA** [comment]
is what you have above a typo? it should be (I think)
```
 {% for i in range(6, 726, 6) %}
```
also I wonder if it should be this instead:
```
   {% set offset_str = i | string %}
   {% set offset_td = "-"+offset_str+"H" | to_timedelta %}
   {% set PDATEnew = PDATE | add_to_datetime(offset_td) %}
- {{ DATA }}/time.{{ SENSOR }}_{{ SAT }}.{{ PDATEnew | to_YMDH }}.ieee_d
{% endfor %}
```
(note you cannot indent the item, unfortunately, it has to be indented as it would be without any looping, but you can indent the Jinja directives.

**Comment by EdwardSafford-NOAA** [comment]
It's not a typo, I was just trying the first 2 cycles as a test and left the iteration over the pdates in place (removing the 2 cycles in the for loop).  

Anyway setting the offset_str separately doesn't seem to matter.  It's still not working.  I'll mess around with it some more.  I surely wish there was some documentation on all this happiness. I guess I'll write that when we're done with obsmon. :(

**Comment by EdwardSafford-NOAA** [comment]
Oh, hang on.  I think you're right.  Maybe that's another ChatGPT hallucination with the range option -- 2 there isn't nsteps it's final value.

**Comment by CoryMartin-NOAA** [comment]
Yeah it should be `range(start, stop, step)`

**Comment by EdwardSafford-NOAA** [comment]
No go.  But I do have some debug:

```
{% set offset_td = "-"+offset_str+"H" | to_timedelta %}
0: TypeError: can only concatenate str (not "datetime.timedelta") to str
```
offset_str is set just ahead of that debug with this:  `{% set offset_str = i | string %}`.

**Comment by CoryMartin-NOAA** [comment]
hmm, that sounds like it is thinking offset_str is a datetime.timedelta... which is odd

**Comment by EdwardSafford-NOAA** [comment]
I have something.  If I do only 1 step per instruction it works, mostly.  

```{% for i in range(6, 12, 6) %}

      {% set offset_str = i | string %}
      {% set offset_td = "-"+offset_str+"H" %}
      {% set fish = offset_td | to_timedelta %}
      {% set PDATEnew = PDATE | add_to_datetime(fish) %}
      - {{ DATA }}/time.{{ SENSOR }}_{{ SAT }}.{{ PDATEnew | to_YMDH }}.ieee_d
      {% endfor %}
```
I'll replace `fish` with something a bit more meaningful; that's me being fast to prove/disprove the concept.  I do have another error later in eva, which must be related to these changes.  I'll see if I can figure that out.

**Comment by CoryMartin-NOAA** [comment]
progress! can end Wednesday on a high note

**Comment by EdwardSafford-NOAA** [comment]
Whew.  I got the eva problem sorted out.  I'll consolidate all of these changes tomorrow and update the plot file for another review.

**Comment by EdwardSafford-NOAA** [comment]
The changes have been consolidated this morning.  If the solution looks good I'll implement the same solution in the other plot template files and move this to non-draft.

**Comment by CoryMartin-NOAA** [comment]
looks great! a lot fewer lines

**Review by CoryMartin-NOAA — APPROVED** [review]
looks great, way more concise!

**Review by kevindougherty-noaa — APPROVED** [review]
Looks awesome. Saves a ton lines of code.

**Pull request merged**
